# version: '3' # Specify the Compose file version

services:
  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres       # Set the PostgreSQL username
      POSTGRES_PASSWORD: postgres # Set the PostgreSQL password
      POSTGRES_DB: postgres     # Set the initial database name
    ports:
      - "5432:5432"  # Map the container port to the host
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist database data
  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - "8080:8080"
volumes:
  # Define a named volume
  postgres-data:
